import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-green-50">

<div className="flex min-h-screen">

  <aside className="w-72 bg-green-800 text-white p-6">

    <h1 className="text-2xl font-bold mb-10">
      🏡 Podere Centoquattro
    </h1>

    <nav className="space-y-3">

      <Link href="/" className="block hover:text-green-300">
        📊 Dashboard
      </Link>

      <Link href="/nuova-pratica" className="block hover:text-green-300">
        📝 Nuova Pratica
      </Link>

      <Link href="/pratiche" className="block hover:text-green-300">
        📋 Tutte le Pratiche
        </Link>

      <Link href="/calendario" className="block hover:text-green-300">
      📅 Calendario
      </Link>

    </nav>

  </aside>

  <main className="flex-1 p-8">
    {children}
  </main>

</div>

</body>

</html>
  );
}
